### ISSUE TITLE
worker.process.pid isn't available in exit handler

### ISSUE THREAD

**Issue by blitmap** [Flipboard/express-cluster#10]
Hello,

I noticed this line:

https://github.com/Flipboard/express-cluster/blob/master/src/index.coffee#L26

When testing this myself it caused an error - the worker object in the exit handler is actually `null`.  It seems like the worker object is already destroyed/collected by the time the exit handler gets it.

What I did in mine was to save the worker process id when I attach the exit handler (yay closures!):

https://github.com/blitmap/coffeescript-snippets/blob/master/script-server.coffee#L31-L34

Also I wanted to point out 2 other things:

1) https://github.com/Flipboard/express-cluster/blob/master/src/index.coffee#L9
  - I believe this should be `config.count or ...`.
  - Also the parseInt() can return NaN.  if you don't want to handle NaN you could just do `+process.env.WORKER_COUNT` to mean essentially the same thing (currently you support negative worker counts).  The funny part is, if `process.env.WORKER_COUNT` is undefined `+undefined` is still `NaN`.  `NaN` is still "falsey" so no problem.  `+` would just be more concise to say the same thing, but `parseInt()` supports interpreting scientific notation.

2) https://github.com/Flipboard/express-cluster/blob/master/src/index.coffee#L18
  - you can write: `0 ... workerCount` here.  `..` is exclusive, `...` is inclusive (<3 coffeescript)

I love how you handle `SIGQUIT` in the master - your exit is much more graceful than mine <3

(sorry for submitting so many issues, I tend to get carried away ~)

**Comment by eden** [comment]
I've address (1) and (2) in #11, but I can't reproduce the null worker handle. Can you give me a small example that demonstrates the problem?

**Comment by blitmap** [comment]
I'm an idiot - I attached the exit handler on the worker (that dies) instead of on the cluster (which I believe is the master process).  Instead of `cluster.on` I had `worker.on`.

So my issue is one I created for myself :-)  You got it right - not sure why i assumed the docs for node were wrong.

Anyway, closing :-)))
