### ISSUE TITLE
Master

### ISSUE THREAD

**Issue by andy1028** [Flipboard/express-cluster#12]
how judge Master process

**Comment by andy1028** [comment]
if(Master){
     // run job
}

**Comment by eden** [comment]
From https://nodejs.org/dist/latest-v4.x/docs/api/cluster.html#cluster_cluster_ismaster
```
require('cluster').isMaster
```

Or:
```
typeof process.env.NODE_UNIQUE_ID === 'undefined'
```

**Comment by andy1028** [comment]
typeof process.env.NODE_UNIQUE_ID === 'undefined'
is unwork

**Comment by eden** [comment]
Hmm you are right... it seems odd, but `cluster.isMaster` will work. I can't explain why since it uses essentially the same test though.

**Comment by andy1028** [comment]
thanks
