### ISSUE TITLE
cluster.isMaster is undefined

### ISSUE THREAD

**Issue by amadeus-torwell** [Flipboard/express-cluster#16]
Hi,

I am having trouble with executing code in master pid:

`const cluster = require('express-cluster');`
`if (cluster.isMaster) {`
`    console.log('xx');`
`}`
`cluster(`
`    worker => {`
`...`

cluster.isMaster is undefined in my example code. What am I doing wrong?

Thanks,
Amadeus

**Comment by eden** [comment]
Ah, `isMaster` is defined on the nodejs module `cluster`, `express-cluster` doesn't expose this property.

https://nodejs.org/dist/latest-v8.x/docs/api/cluster.html#cluster_cluster_ismaster

**Comment by amadeus-torwell** [comment]
Oh I see, how would I be using it in my code?

> You should guard any code that should only be run in the master behind a check of process.env.NODE_UNIQUE_ID or a call to node's cluster.isMaster

**Comment by eden** [comment]
you can use either, to use node's built-in cluster:

```
const nodeCluster = require('cluster')
const cluster = require('express-cluster');
if (nodeCluster.isMaster) {
console.log('xx');
}
cluster(
worker => {
...
```

**Comment by amadeus-torwell** [comment]
Thanks 👍
