### ISSUE TITLE
exiting worker: support showing signal that killed it

### ISSUE THREAD

**Issue by blitmap** [Flipboard/express-cluster#9]
Hello,

I was looking over the source again and I noticed this line:

https://github.com/Flipboard/express-cluster/blob/master/src/index.coffee#L26

From how the documentation reads, it sounds like `signal` is sometimes available (if the worker was actually killed by a signal) - while the exit code is always available: https://nodejs.org/api/cluster.html#cluster_event_exit_1

I wound up writing it like this in my project, I thought it might be of use to you:

https://github.com/blitmap/coffeescript-snippets/blob/master/script-server.coffee#L34

**Comment by eden** [comment]
Good catch.
